# small .ics writer, no extra dependency
import hashlib
from datetime import datetime, timedelta
from typing import Dict, List, Optional


def _esc(s: str) -> str:
    return (s or "").replace("\\", "\\\\").replace(";", "\\;").replace(",", "\\,").replace("\r\n", "\n").replace("\n", "\\n")


def _fold(line: str) -> List[str]:
    raw = line.encode("utf-8")
    if len(raw) <= 75:
        return [line]
    out, cur = [], b""
    for ch in line:
        b = ch.encode("utf-8")
        limit = 75 if not out else 74
        if len(cur) + len(b) > limit:
            out.append(cur.decode("utf-8"))
            cur = b
        else:
            cur += b
    out.append(cur.decode("utf-8"))
    return [out[0]] + [" " + p for p in out[1:]]


def event_for_deadline(d: Dict, analysis_title: str, prereqs: Optional[List[str]] = None) -> Optional[Dict]:
    if not d.get("due_at"):
        return None
    desc = [f"From: {analysis_title}", f"Type: {d.get('kind', 'unknown')} deadline"]
    if d.get("date_text"):
        desc.append(f"Source wording: {d['date_text']}")
    if d.get("assumed_anchor"):
        desc.append("NOTE: counted from when the document was analyzed - verify the real start time.")
    if d.get("needs_verification"):
        desc.append("NEEDS VERIFICATION against the original document.")
    if prereqs:
        desc.append("Do first: " + "; ".join(prereqs))
    desc.append("Generated by LifeOps AI. Check the original document - this is organisation help, not professional advice.")
    return {
        "uid": hashlib.sha1(f"{d['id']}".encode()).hexdigest()[:20] + "@lifeops.ai",
        "summary": f"Deadline: {d['label']}",
        "start": d["due_at"],
        "all_day": len(d["due_at"]) == 10,
        "description": "\n".join(desc),
    }


def build_ics(events: List[Dict], now: Optional[datetime] = None) -> str:
    now = now or datetime.utcnow()
    lines = ["BEGIN:VCALENDAR", "VERSION:2.0", "PRODID:-//LifeOps AI//Deadline Shield//EN", "CALSCALE:GREGORIAN", "METHOD:PUBLISH"]
    for e in events:
        lines += ["BEGIN:VEVENT", f"UID:{e['uid']}", f"DTSTAMP:{now:%Y%m%dT%H%M%SZ}"]
        start = datetime.fromisoformat(e["start"])
        if e["all_day"]:
            lines += [f"DTSTART;VALUE=DATE:{start:%Y%m%d}", f"DTEND;VALUE=DATE:{(start + timedelta(days=1)):%Y%m%d}"]
        else:  # floating local time (no timezone claimed)
            lines += [f"DTSTART:{start:%Y%m%dT%H%M%S}", f"DTEND:{(start + timedelta(minutes=30)):%Y%m%dT%H%M%S}"]
        lines += [f"SUMMARY:{_esc(e['summary'])}", f"DESCRIPTION:{_esc(e['description'])}"]
        for trig, label in (("-P1D", "1 day before"), ("-PT1H", "1 hour before")):
            lines += ["BEGIN:VALARM", "ACTION:DISPLAY", f"DESCRIPTION:{_esc(e['summary'] + ' (' + label + ')')}", f"TRIGGER:{trig}", "END:VALARM"]
        lines.append("END:VEVENT")
    lines.append("END:VCALENDAR")
    folded: List[str] = []
    for l in lines:
        folded.extend(_fold(l))
    return "\r\n".join(folded) + "\r\n"
